name: edgex-device-thingy52
base: core18
version: "replace-me"
version-script: |
  echo 0.7.1-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
license: Apache-2.0
summary: EdgeX Device Service for Nordic Thingy52 BLE sensor
description: |
  Interact with the Nordic Thingy52 Bluetooth Low Energy sensor platform using
  EdgeX Foundry.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: i386

apps:
  device-thingy52:
    command: bin/go-service-wrapper.sh device-thingy52
    daemon: simple
    restart-condition: always
    plugs: 
      - network
      - network-bind
      - bluez

parts:
  ci-snaps-common:
    plugin: dump
    source: https://github.com/anonymouse64/ci-snaps-common.git
    source-branch: feature/initial
    stage:
      - bin/*
    prime:
      - bin/go-service-wrapper.sh
  go:
    plugin: nil
    source: snap/local
    build-packages: [curl]
    override-build: |
      # use dpkg architecture to figure out our target arch
      # note - we specifically don't use arch
      case "$(dpkg --print-architecture)" in
        amd64)
          FILE_NAME=go1.11.9.linux-amd64.tar.gz
          FILE_HASH=e88aa3e39104e3ba6a95a4e05629348b4a1ec82791fb3c941a493ca349730608
          ;;
        arm64)
          FILE_NAME=go1.11.9.linux-arm64.tar.gz
          FILE_HASH=892ab6c2510c4caa5905b3b1b6a1d4c6f04e384841fec50881ca2be7e8accf05
          ;;
        armhf)
          FILE_NAME=go1.11.9.linux-armv6l.tar.gz
          FILE_HASH=f0d7b039cae61efdc346669f3459460e3dc03b6c6de528ca107fc53970cba0d1
          ;;
        i386)
          FILE_NAME=go1.11.9.linux-386.tar.gz
          FILE_HASH=0fa4001fcf1ef0644e261bf6dde02fc9f10ae4df6d74fda61fc4d3c3cbef1d79
          ;;
      esac
      # download the archive, failing on ssl cert problems
      curl https://dl.google.com/go/$FILE_NAME -O
      echo "$FILE_HASH $FILE_NAME" > sha256
      sha256sum -c sha256 | grep OK
      tar -C $SNAPCRAFT_STAGE -xf go*.tar.gz --strip-components=1
    prime:
      - "-*"
    after: [ci-snaps-common]
  device-thingy52:
    source: .
    plugin: make
    after: [go]
    build-packages: [mercurial, git, build-essential]
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cd $SNAPCRAFT_PART_SRC
      make build

      install -DT "./cmd/device-thingy52" "$SNAPCRAFT_PART_INSTALL/bin/device-thingy52"
      install -d "$SNAPCRAFT_PART_INSTALL/config/device-thingy52/res/"

      # Override 'LogFile'      
      cat "./cmd/res/configuration.toml" | \
        sed -e s:\"./device-thingy52.log\":\'\$SNAP_COMMON/device-thingy52.log\': > \
        "$SNAPCRAFT_PART_INSTALL/config/device-thingy52/res/configuration.toml"

      # install device profile as well
      install -T "./cmd/res/device.thingy52.yaml" \
        "$SNAPCRAFT_PART_INSTALL/config/device-thingy52/res/device.thingy52.yaml"

      # install license and attribution.txt
      # TODO: add attribution.txt to this repo
      # install -DT "./cmd/Attribution.txt" \
      #    "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-thingy52/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-thingy52/LICENSE"

